export const AUTH_USER='auth_user';
export const UNAUTH_USER='unauth_user';
export const AUTH_ERROR='auth_error';
export const FETCH_MESSAGE='fetch_message';
export const UPDATE_USER = 'update_user';
export const FETCH_JOB = 'fetch_job';
export const SAVE_JOB = 'saved_job';
export const USERS = 'users';
export const EDIT_PROFILE = 'edit_profile';
export const FILTERED_CASES = 'FILTERED_CASES';
export const FILTERED_STUDENTS = 'FILTERED_STUDENTS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_MOUNT = 'PASSWORD_RESET_MOUNT';
export const CSV_EXPORT = 'CSV_EXPORT'