export const AUTH_USER='auth_user';
export const UNAUTH_USER='unauth_user';
export const AUTH_ERROR='auth_error';
export const FETCH_MESSAGE='fetch_message';
export const UPDATE_USER = 'update_user';
export const FETCH_JOB = 'fetch_job';
export const SAVE_JOB = 'saved_job';
export const USERS = 'users';
export const EDIT_PROFILE = 'edit_profile';
export const FILTERED_CASES = 'FILTERED_CASES'